export default {
  initialColorMode: "light",
  colors: {
    text: "#000",
    background: "#f2f2f2",
    headerText: "black",
    headerBG: "rgba(255, 255, 255, 0.97)",
    headerShadow: "0 16px 20px 0 rgba(0,0,0,0.2)",
    footerBG: "black",
    footerText: "#bdbdbd",
    cardHeader: "black",
    cardBG: "#ffffff",
    cardText: "black",
    cardLink: "black",
    cardShadow: "rgba(0,0,0,0.2)",
    heroBG: "white",
    heroText: "black",
    buttonBorder: "black",
    buttonBG: "#ffffff",
    buttonText: "black",
    avatarBG: "black",
    avatarText: "white",
    inputBorder: "black",
    inputText: "black",
    inputBG: "#f2f2f2",
    curtainText: "black",
    curtainBG: "white",
    hamburgerBG: "black",
    modes: {
      dark: {
        text: "#fff",
        background: "#000",
        headerText: "white",
        headerBG: "#171717",
        headerShadow: "0 16px 20px 0 rgba(0,0,0,0.2)",
        footerBG: "#171717",
        footerText: "#dedede",
        cardHeader: "white",
        cardBG: "#171717",
        cardText: "#dedede",
        cardLink: "white",
        cardShadow: "0 16px 20px 0 rgba(0,0,0,0.2)",
        heroBG: "white",
        heroText: "black",
        buttonBorder: "white",
        buttonBG: "#121212",
        buttonText: "white",
        avatarBG: "white",
        avatarText: "black",
        inputBorder: "white",
        inputText: "white",
        inputBG: "black",
        curtainText: "white",
        curtainBG: "black",
        hamburgerBG: "white",
      },
    },
  },
}
